const professionalData = [{
        id: 1,
        name: "Amos",
        profession: "teacher",
        category: "teaching",
        image: "./images/img 1.jpg",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam, eligendi!",
    },
    {
        id: 2,
        name: "peter",
        profession: "Nurse",
        category: "nursing",
        image: "./images/img 2.jpg",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam, eligendi!",
    },
    {
        id: 3,
        name: "paul",
        profession: "acconutant",
        category: "accounting",
        image: "./images/img 3.jpg",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam, eligendi!",
    },
    {
        id: 4,
        name: "Michael",
        profession: "teacher",
        category: "teaching",
        image: "./images/campus-2.jpeg",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam, eligendi!",
    },
    {
        id: 5,
        name: "Gideon",
        profession: "Nurse",
        category: "nursing",
        image: "./images/img 5.jpeg",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam, eligendi!",
    },
    {
        id: 6,
        name: "Tutu",
        profession: "accountant",
        category: "accounting",
        image: "./images/img 6.jpeg",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam, eligendi!",
    },
    {
        id: 7,
        name: "Joe",
        profession: "teacher",
        category: "teaching",
        image: "./images/img 7.jpg",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam, eligendi!",
    },
    {
        id: 8,
        name: "Prince",
        profession: "nurse",
        category: "nursing",
        image: "./images/img 8.jpg",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam, eligendi!",
    },
    {
        id: 9,
        name: "Bright",
        profession: "accountant",
        category: "accounting",
        image: "./images/img 9.jpg",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam, eligendi!",
    },
    {
        id: 10,
        name: "Amos",
        profession: "teacher",
        category: "teaching",
        image: "./images/img 10.jpg",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam, eligendi!",
    },
    {
        id: 11,
        name: "Amos",
        profession: "police",
        category: "security",
        image: "./images/img 10.jpg",
        description: "Lorem ipsum dolor sit, amet consectetur adipisicing elit. Veniam, eligendi!",
    },

];

export default professionalData;